# Generated by Django 6.1.1 on 2026-09-23 20:19

import acervo.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(blank=True, max_length=80)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
            ],
            options={
                'verbose_name_plural': 'autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='data de cadastro')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('isbn', models.CharField(max_length=17, unique=True, verbose_name='ISBN')),
                ('editora', models.CharField(blank=True, max_length=100)),
                ('ano_publicacao', models.PositiveIntegerField(verbose_name='ano de publicação')),
                ('sinopse', models.TextField(blank=True)),
                ('autores', models.ManyToManyField(related_name='livros', to='acervo.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código de tombo')),
                ('data_aquisicao', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de aquisição')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para exemplares perdidos, danificados ou em manutenção.', verbose_name='em circulação')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='acervo.livro')),
            ],
            options={
                'verbose_name_plural': 'exemplares',
                'ordering': ['livro__titulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data da reserva')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando na fila'), ('disponivel', 'Disponível para retirada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='aguardando', max_length=12)),
                ('data_limite_retirada', models.DateField(blank=True, null=True, verbose_name='retirar até')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.membro')),
            ],
            options={
                'ordering': ['data_reserva', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do empréstimo')),
                ('data_prevista_devolucao', models.DateField(default=acervo.models.data_prevista_padrao, verbose_name='devolução prevista')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='data da devolução')),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('multa_paga', models.BooleanField(default=False, verbose_name='multa paga')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.exemplar')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.membro')),
            ],
            options={
                'verbose_name': 'empréstimo',
                'ordering': ['-data_emprestimo', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('data_devolucao__isnull', True)), fields=('exemplar',), name='um_emprestimo_aberto_por_exemplar')],
            },
        ),
    ]
